FROM python:3.12-slim

RUN apt-get update && \
    apt-get install -y openjdk-17-jdk ca-certificates-java && \
    apt-get clean && \
    update-ca-certificates -f && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH="$JAVA_HOME/bin:$PATH"

WORKDIR /app

COPY pyproject.toml .
COPY jobs/ jobs/
COPY tests/ tests/

RUN pip install --no-cache-dir -r tests/requirements.txt

CMD ["pytest", "-s", "--cov", "jobs/", "--cov-report=html:test_results/"]
