services:
  spark-app:
    image: bitnami/spark:latest
    container_name: spark-app
    environment:
      - SPARK_MODE=client
      - SPARK_MASTER_URL=spark://spark-master:7077
    user: root
    volumes:
      - ../app:/app
    working_dir: /app
    command:
      - bash
      - -c
      - |
        pip install -r requirements.txt
        spark-submit --master spark://spark-master:7077 main.py
    networks:
      - spark-net

networks:
  spark-net:
